# Generated by Django 2.2 on 2020-01-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop_stocks', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Return Name Sample Request', max_length=254)),
                ('sample_quantity', models.CharField(blank=True, default='', max_length=254, verbose_name='Sample Quantity (KGs)')),
                ('delivery_destination', models.CharField(blank=True, choices=[('agvoffice', 'AGV Ltd. Timau Head Office'), ('cargil', 'Cargil, Nakuru'), ('nairobi', 'EAML Labs, Nairobi')], default='', max_length=254, verbose_name='Delivery Destination')),
                ('request_status', models.CharField(blank=True, choices=[('created', 'Request Created'), ('pending', 'Pending'), ('shipped', 'Sample Shipped'), ('delivered', 'Sample Delivered')], default='', max_length=254, verbose_name='Request Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_request_creator', to=settings.AUTH_USER_MODEL)),
                ('crop_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_requests', to='crop_stocks.CropStockModel', verbose_name='Crop Requested')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.FarmModel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_request_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
