# Generated by Django 2.2 on 2020-01-19 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(default='Trailer Reg. Number', max_length=254)),
                ('chassis_number', models.CharField(default='', max_length=254, verbose_name='Trailer Chassis Number')),
                ('color', models.CharField(default='', max_length=254, verbose_name='Trailer Color')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_creator', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='transporters.TransportModel', verbose_name='Trailer Transporter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
