# Generated by Django 2.2 on 2020-01-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpaymentmodel',
            name='date_overdue',
        ),
    ]
