# Generated by Django 2.2 on 2020-01-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('customer_contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(default='Agventure Ltd.', max_length=254, verbose_name='Agventure Ltd. (Buyer)')),
                ('farm_contract_code', models.CharField(default='xyBMAr2019', max_length=254, verbose_name='Farm Contract Code')),
                ('ordered_quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Ordered Quantity (KGs)')),
                ('bag_type', models.CharField(choices=[('', 'Specify Interested Bag Type'), ('1', '90 KG'), ('2', '50 KG')], default='1', max_length=254, verbose_name='Bag Type')),
                ('bulk_bags', models.CharField(choices=[('', 'Specify Interested Bag Type'), ('1', '90 KG'), ('2', '50 KG')], default='1', max_length=254, verbose_name='Bulk or Bags Order Type')),
                ('total_bags', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='No. of Bags')),
                ('farm_kg_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Farm Price/KG (KSH)')),
                ('farm_bag_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Farm Price/Bag (KSH)')),
                ('total_farm_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Farm Selling Price')),
                ('farm_tolerance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Tolerance +/-')),
                ('collection_weight_bridge', models.CharField(blank=True, default='', max_length=254, verbose_name='Farm of Collection Weigh Bridge')),
                ('delivery_weigh_bridge', models.CharField(blank=True, default='', max_length=254, verbose_name='Crop Delivery Destination (Cust. Point)')),
                ('quality_specs', models.CharField(default='As per Sample Results', max_length=254, verbose_name='Crop Quality Specifications')),
                ('offloading_fees', models.TextField(blank=True, default='No Offloading Fees for Vehicles are to be Levied by the Buyer', verbose_name='Offloading Fees')),
                ('other_conditions', models.TextField(blank=True, default='', verbose_name='Other Conditions')),
                ('governing_terms', models.TextField(blank=True, default='Kenyan Law Shall Apply', verbose_name='Governing Terms')),
                ('whole_agreement', models.TextField(blank=True, default='', verbose_name='Whole Agreement')),
                ('rejection_procedure', models.TextField(blank=True, default='Rejection can take place at the Farm. Once Accepted and Carried, no Rejection can Take Place. ', verbose_name='Rejection Procedure')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Contract Date')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_contract_creator', to=settings.AUTH_USER_MODEL)),
                ('customer_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_contracts', to='customer_contracts.CustomerContractModel', verbose_name='Customer Contract FK')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_farmer', to='farms.FarmModel', verbose_name='Farm Selling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_contract_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
