# Generated by Django 2.2 on 2020-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterestmodel',
            name='bag_type',
            field=models.CharField(choices=[('', 'Specify Interested Bag Type'), ('90', '90 KG'), ('50', '50 KG')], default=1, max_length=254, verbose_name='Customer Bag Type'),
        ),
        migrations.AlterField(
            model_name='customerinterestmodel',
            name='farm_approval',
            field=models.CharField(choices=[('', 'Please Approve/Disapprove the Cust. Order'), ('approved', 'Order Approved'), ('not approved', 'Order Not Approved')], default='', max_length=254, verbose_name='Farm App/Disapp.'),
        ),
        migrations.AlterField(
            model_name='customerinterestmodel',
            name='order_type',
            field=models.CharField(choices=[('', 'Specify Supply Order in Bulk/Bags'), ('bulk', 'Bulk Order'), ('bags', 'Bags Order')], default='', max_length=254, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='customerinterestmodel',
            name='payment_terms',
            field=models.CharField(choices=[('', 'Specify Customer Payment Terms '), ('cash', 'Cash'), ('prepaid', 'Pre-Paid'), ('30days', 'Payment after 30 Days'), ('60days', 'Payment after 60 Days')], default='', max_length=254, verbose_name='Payment Terms'),
        ),
    ]
