# Generated by Django 2.2 on 2020-01-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254, verbose_name='Customer Name')),
                ('type', models.CharField(blank=True, choices=[('', 'Specify The Customer Type'), ('individual', 'Individual'), ('company', 'Company')], default='', max_length=254, verbose_name='Customer Type')),
                ('category', models.CharField(blank=True, choices=[('', 'Specify Customer Category'), ('feeds', 'Animal Feeds'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD'), ('usd', 'USD')], default='', max_length=254, verbose_name='DCustomer Category')),
                ('department', models.CharField(choices=[('', 'Specify The Customer Department'), ('1000', '1000 Administration'), ('1001', '1001 Centre of Excellence'), ('2000', '2000 Crop Sales'), ('3000', '3000 Marketing'), ('4000', '4000 Chemicals and Fertilizers'), ('5000', '5000 Timau Processing'), ('6000', '6000 Nakuru Processing'), ('7000', '7000 Green Peas'), ('8000', '8000 Operations-Nairobi'), ('8001', '8001 Pulses'), ('8999', '8999 Others'), ('9000', '9000 Operations-Nakuru'), ('9999', '9999 Seed-Business')], default='1', max_length=254, verbose_name='Customer Department')),
                ('payment_terms', models.CharField(blank=True, choices=[('', 'Specify The Customer Department'), ('cash', 'Cash'), ('prepaid', 'Pre Paid'), ('30days', 'Payment after 30 Days'), ('60days', 'Payment after 60 Days')], default='', max_length=254, verbose_name='Payment Terms')),
                ('currency', models.CharField(blank=True, choices=[('', 'Specify Currency of Trade'), ('ksh', 'KSH'), ('usd', 'USD')], default='', max_length=254, verbose_name='Currency')),
                ('reg_no', models.CharField(blank=True, default='', max_length=254, verbose_name='Customer Reg. Number')),
                ('vat_reg', models.CharField(blank=True, default='', max_length=254, verbose_name='Customer VAT Reg.')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
