# Generated by Django 2.2 on 2020-01-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Farm Name')),
                ('short_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Farm Abbv.')),
                ('mobile', models.CharField(blank=True, default='', max_length=254, verbose_name='Farm Telephone No.')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Farm Email')),
                ('region', models.CharField(blank=True, default='', max_length=254, verbose_name='Farm Region')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_create', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
